# Generated by Django 5.2.4 on 2025-07-14 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0002_viloyatlar_delete_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mahallalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('context', models.TextField(blank=True)),
                ('created_at', models.IntegerField()),
                ('updated_at', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tumanlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('context', models.TextField(blank=True)),
                ('created_at', models.IntegerField()),
                ('updated_at', models.IntegerField()),
                ('viloyat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configapp.viloyatlar')),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='mahallalar',
            name='tumanlar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configapp.tumanlar'),
        ),
    ]
