# Generated by Django 5.2.4 on 2025-07-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0003_mahallalar_tumanlar_delete_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahallalar',
            name='created_at',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mahallalar',
            name='updated_at',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tumanlar',
            name='created_at',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tumanlar',
            name='updated_at',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
